### ISSUE TITLE
UI additions: event number and major event code block

### ISSUE THREAD

**Issue by jduan00** [eagle1-sys/whereis-ui-v0#30]
## UI mock-up for v0.2.0

<img width="764" alt="Image" src="https://github.com/user-attachments/assets/c93b9ba7-0dc7-476c-ba2d-80e6153f0b5a" />

## Font
```css
@font-face {
  font-family: 'Carattere';
  font-style: normal;
  font-weight: 400;
  src: url(https://cdn.eg1.io/fonts/carattere.woff2) format('woff2');
}
```

## Whereis Event codes
https://github.com/eagle1-sys/whereis-api-v0/blob/main/metadata/status_codes.json
